name: prompt
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - contourpy=1.0.6
  - cudatoolkit=11.8.0
  - cudnn=8.4.1.50
  - cycler=0.11.0
  - dbus=1.13.18
  - expat=2.5.0
  - fontconfig=2.14.1
  - fonttools=4.38.0
  - freetype=2.12.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2021.4.0
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.14
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=10.0.1
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.74.1
  - libhwloc=2.8.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libpng=1.6.39
  - libpq=12.9
  - libprotobuf=3.21.12
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.0
  - libuuid=2.32.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzlib=1.2.13
  - llvm-openmp=15.0.6
  - magma=2.6.2
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - mkl=2022.2.1
  - munkres=1.1.4
  - nccl=2.14.3.1
  - ncurses=6.3
  - ninja=1.11.0
  - nspr=4.35
  - nss=3.82
  - numpy=1.24.0
  - openssl=1.1.1s
  - packaging=22.0
  - pcre2=10.40
  - pillow=9.3.0
  - pip=22.3.1
  - ply=3.11
  - pycparser=2.21
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - python=3.9.15
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.13.0
  - pytorch-gpu=1.13.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - scikit-learn=1.1.1
  - setuptools=65.5.0
  - sip=6.6.2
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.40.0
  - tbb=2021.7.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - typing_extensions=4.4.0
  - tzdata=2022g
  - unicodedata2=15.0.0
  - wheel=0.37.1
  - xz=5.2.8
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - aiohttp==3.8.3
      - aiosignal==1.3.1
      - async-timeout==4.0.2
      - attrs==22.2.0
      - charset-normalizer==2.1.1
      - datasets==2.8.0
      - dill==0.3.6
      - filelock==3.8.2
      - frozenlist==1.3.3
      - fsspec==2022.11.0
      - huggingface-hub==0.11.1
      - idna==3.4
      - joblib==1.2.0
      - multidict==6.0.3
      - multiprocess==0.70.14
      - openprompt==1.0.1
      - pandas==1.5.2
      - protobuf==3.20.1
      - pyarrow==10.0.1
      - pytz==2022.7
      - pyyaml==6.0
      - regex==2022.10.31
      - requests==2.28.1
      - responses==0.18.0
      - rouge==1.0.0
      - scipy==1.9.3
      - sentencepiece==0.1.96
      - tensorboardx==2.5.1
      - tokenizers==0.13.2
      - tqdm==4.64.1
      - transformers==4.25.1
      - urllib3==1.26.13
      - xxhash==3.1.0
      - yacs==0.1.8
      - yarl==1.8.2

